# Generated by Django 6.0 on 2025-12-26 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_music_genre', models.CharField(blank=True, max_length=50)),
                ('enable_voice_detection', models.BooleanField(default=True)),
                ('enable_face_detection', models.BooleanField(default=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('average_confidence', models.FloatField(blank=True, null=True)),
                ('total_emotions_detected', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_type', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral'), ('worried', 'Worried')], max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score (0-1)')),
                ('source', models.CharField(choices=[('face', 'Facial Recognition'), ('voice', 'Voice Analysis'), ('combined', 'Face + Voice')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw emotion detection data', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='emotions.usersession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='emotions_em_user_id_f44594_idx'), models.Index(fields=['emotion_type'], name='emotions_em_emotion_a66f41_idx')],
            },
        ),
    ]
