# Generated by Django 6.0 on 2025-12-26 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('most_common_emotion', models.CharField(max_length=20)),
                ('emotion_distribution', models.JSONField(help_text='Distribution of emotions over period')),
                ('mood_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20)),
                ('most_helpful_content_type', models.CharField(blank=True, max_length=20)),
                ('total_recommendations_received', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of emotional patterns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emotion Insight',
                'verbose_name_plural': 'Emotion Insights',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Motivational Text'), ('music', 'Music/Song'), ('activity', 'Activity Suggestion'), ('quote', 'Inspirational Quote')], max_length=20)),
                ('emotion_trigger', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral'), ('worried', 'Worried')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Main content: text, lyrics, description')),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('spotify_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Estimated duration for activity', null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.IntegerField(default=0, help_text='How many times this was recommended')),
            ],
            options={
                'ordering': ['-usage_count', 'emotion_trigger'],
                'indexes': [models.Index(fields=['emotion_trigger', 'content_type'], name='recommendat_emotion_f29ad7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_emotion', models.CharField(max_length=20)),
                ('emotion_confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_completed', models.BooleanField(default=False, help_text='For activities: did user complete it?')),
                ('user_feedback', models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recommendation History',
                'verbose_name_plural': 'User Recommendation Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='recommendat_user_id_6cdfa7_idx'), models.Index(fields=['recommendation'], name='recommendat_recomme_d2fb99_idx')],
            },
        ),
    ]
