# Generated by Django 6.0 on 2025-12-26 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('initial_emotion', models.CharField(blank=True, help_text="User's emotion at session start", max_length=20, null=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_summary', models.TextField(blank=True, help_text='Summary of conversation so far')),
                ('user_concerns', models.JSONField(default=list, help_text="List of user's expressed concerns")),
                ('suggested_topics', models.JSONField(default=list, help_text='Topics bot has suggested')),
                ('emotion_history', models.JSONField(default=list, help_text='History of detected emotions during chat')),
                ('mood_trend', models.CharField(blank=True, help_text='improving, declining, stable', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=4)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('detected_emotion', models.CharField(blank=True, help_text="User's emotion when message was sent", max_length=20, null=True)),
                ('emotion_confidence', models.FloatField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, help_text='Type of bot response: advice, motivation, question, etc.', max_length=50, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='chatbot_cha_session_488328_idx')],
            },
        ),
    ]
